
Sys.setenv(FALK_EXTENDED_USER_RIGHTS= "[{\"A\":107,\"R\":\"SC\",\"U\":706078},{\"A\":107,\"R\":\"LU\",\"U\":706078},{\"A\":107,\"R\":\"LU\",\"U\":700720},{\"A\":107,\"R\":\"LU\",\"U\":700720}]")
Sys.setenv(MYSQL_DB_LOG="db_log")
Sys.setenv(MYSQL_DB_AUTOREPORT="db_autoreport")
Sys.setenv(MYSQL_DB_DATA="intensivregisterreportdatastaging")
Sys.setenv(MYSQL_HOST="db")
Sys.setenv(MYSQL_USER="root")
Sys.setenv(MYSQL_PASSWORD="root")
Sys.setenv(FALK_APP_ID="107")
Sys.setenv(FALK_USER_EMAIL="jesus@sky.no")
Sys.setenv(FALK_USER_FULLNAME="Reidar")
Sys.setenv(USERORGID="pilot")
Sys.setenv(SHINYPROXY_USERNAME="sivh")
Sys.setenv(SHINYPROXY_USERGROUPS="pilot")
Sys.setenv(R_RAP_INSTANCE="QAC")
Sys.setenv(R_RAP_CONFIG_PATH="data-raw/config")
